version: '3.8'  # Vous pouvez supprimer cette ligne si vous recevez un avertissement

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: SNCF-Ticketing
      MYSQL_USER: root
      MYSQL_PASSWORD: 0000
    ports:
      - "3306:3306"
